version: '3.7'

services:
  postgresql:
    container_name: mover_prod
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mover
    ports:
      - "5432:5432"
    networks:
      - mover_network

  postgresql_test:
    container_name: mover_test
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mover_test
    ports:
      - "5433:5432"
    networks:
      - mover_network

networks:
  mover_network: