version: '3.7'

services:
  mysql:
    container_name: mover_prod
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mover
    ports:
      - "3306:3306"
    networks:
      - mover_network

  mysql_test:
    container_name: mover_test
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mover_test
    ports:
      - "3307:3306"
    networks:
      - mover_network

networks:
  mover_network: