spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 8
      minimum-idle: 4
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: false

  mail:
    host: host
    port: 1105
    username: mail_username
    password: xyz@123
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: false
          socketFactory:
            port: 1100
            class: javax.net.ssl.SSLSocketFactory

mover:
  root-user: ${ROOT_USER}
  root-user-password: ${ROOT_USER_PASSWORD}
  secret-key: ${SECRET_KEY}