CREATE TABLE `tb_transaction` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) DEFAULT NULL,
  `category_type` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `due_date` date NOT NULL,
  `frequency` varchar(255) DEFAULT NULL,
  `hour` time(6) NOT NULL,
  `installment` int DEFAULT NULL,
  `paid` bit(1) NOT NULL,
  `payment_date` date DEFAULT NULL,
  `payment_type` varchar(255) DEFAULT NULL,
  `predicted` bit(1) NOT NULL,
  `refund` bit(1) NOT NULL,
  `signature` varchar(255) DEFAULT NULL,
  `transaction_type` varchar(255) DEFAULT NULL,
  `value` decimal(38,2) NOT NULL,
  `account_id` bigint NOT NULL,
  `card_id` bigint DEFAULT NULL,
  `contract_id` bigint DEFAULT NULL,
  `partner_id` bigint DEFAULT NULL,
  `subcategory_id` bigint NOT NULL,
  `vehicle_id` bigint DEFAULT NULL,
  `last_installment` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_transaction_account_id` (`account_id`),
  KEY `fk_transaction_card_id` (`card_id`),
  KEY `fk_transaction_contract_id` (`contract_id`),
  KEY `fk_transaction_partner_id` (`partner_id`),
  KEY `fk_transaction_subcategory_id` (`subcategory_id`),
  KEY `fk_transaction_vehicle_id` (`vehicle_id`),
  CONSTRAINT `fk_transaction_account_id` FOREIGN KEY (`account_id`) REFERENCES `tb_account` (`id`),
  CONSTRAINT `fk_transaction_card_id` FOREIGN KEY (`card_id`) REFERENCES `tb_card` (`id`),
  CONSTRAINT `fk_transaction_contract_id` FOREIGN KEY (`contract_id`) REFERENCES `tb_contract` (`id`),
  CONSTRAINT `fk_transaction_partner_id` FOREIGN KEY (`partner_id`) REFERENCES `tb_partner` (`id`),
  CONSTRAINT `fk_transaction_subcategory_id` FOREIGN KEY (`subcategory_id`) REFERENCES `tb_subcategory` (`id`),
  CONSTRAINT `fk_transaction_vehicle_id` FOREIGN KEY (`vehicle_id`) REFERENCES `tb_vehicle` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33163 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;