CREATE TABLE `tb_client` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) DEFAULT NULL,
  `birth_date` date NOT NULL,
  `cell_phone` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `complement` varchar(255) DEFAULT NULL,
  `cpf_cnpj` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `mother_name` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `neighborhood` varchar(255) NOT NULL,
  `number` varchar(255) NOT NULL,
  `postal_code` varchar(255) NOT NULL,
  `public_place` varchar(255) NOT NULL,
  `rg` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `telephone` varchar(255) DEFAULT NULL,
  `type_person` enum('NATURAL_PERSON') NOT NULL,
  `user_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_user_id` (`user_id`),
  CONSTRAINT `fk_client_user_id` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;